import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://demo.automationtesting.in/Register.html');
  await expect(page.getByRole('link', { name: 'image not displaying' })).toBeVisible();
  await expect(page.locator('h1')).toContainText('Automation Demo Site');
  await expect(page.locator('h2')).toContainText('Register');
  await expect(page.locator('#basicBootstrapForm')).toContainText('Full Name*');
  await expect(page.getByPlaceholder('First Name')).toBeVisible();
  await page.getByPlaceholder('First Name').click();
  await page.getByPlaceholder('First Name').fill('Jones');
  await page.getByPlaceholder('First Name').press('Tab');
  await expect(page.getByPlaceholder('Last Name')).toBeVisible();
  await page.getByPlaceholder('Last Name').click();
  await page.getByPlaceholder('Last Name').fill('Kapil');
  await expect(page.locator('#basicBootstrapForm')).toContainText('Address');
  await expect(page.locator('textarea')).toBeVisible();
  await page.locator('textarea').click();
  await page.locator('textarea').fill('No-8, thiruvidaimarudur,kumbakonam');
  await expect(page.locator('#basicBootstrapForm')).toContainText('Email address*');
  await expect(page.locator('input[type="email"]')).toBeVisible();
  await page.locator('input[type="email"]').click();
  await page.locator('input[type="email"]').fill('jones01@yopmail.com');
  await expect(page.locator('#basicBootstrapForm')).toContainText('Phone*');
  await expect(page.locator('input[type="tel"]')).toBeVisible();
  await page.locator('input[type="tel"]').click();
  await page.locator('input[type="tel"]').fill('9876543210');
  await expect(page.locator('#basicBootstrapForm')).toContainText('Gender*');
  await expect(page.getByText('Male', { exact: true })).toBeVisible();
  await page.getByLabel('Male', { exact: true }).check();
  await expect(page.locator('#basicBootstrapForm')).toContainText('Hobbies');
  await expect(page.locator('#basicBootstrapForm')).toContainText('Cricket');
  await expect(page.locator('#basicBootstrapForm')).toContainText('Movies');
  await expect(page.locator('#basicBootstrapForm')).toContainText('Hockey');
  await page.locator('#checkbox1').check();
  await expect(page.locator('#basicBootstrapForm')).toContainText('Languages');
  await expect(page.locator('#msdd')).toBeVisible();
  await page.locator('#msdd').click();
  await page.getByText('English').click();
  await page.getByText('Languages English Arabic').click();
  await expect(page.locator('#msdd')).toContainText('English');
  await page.locator('#msdd').getByText('English').click();
  await page.locator('li').filter({ hasText: 'Arabic' }).click();
  await page.locator('div').filter({ hasText: /^Arabic$/ }).locator('span').click();
  await page.locator('#msdd').click();
  await page.locator('div').filter({ hasText: 'Full Name* Address Email' }).nth(1).click();
  await expect(page.locator('#basicBootstrapForm')).toContainText('Skills');
  await expect(page.locator('#Skills')).toBeVisible();
  await page.locator('#Skills').selectOption('Javascript');
  await expect(page.locator('#basicBootstrapForm')).toContainText('Country*');
  await expect(page.locator('#countries')).toBeVisible();
  await expect(page.locator('#basicBootstrapForm')).toContainText('Select Country :');
  await expect(page.getByLabel('', { exact: true })).toBeVisible();
  await page.getByLabel('', { exact: true }).click();
  await page.locator('input[type="search"]').fill('india');
  await page.locator('input[type="search"]').press('Enter');
  await expect(page.locator('#basicBootstrapForm')).toContainText('Date Of Birth');
  await expect(page.locator('#yearbox')).toBeVisible();
  await page.locator('#yearbox').selectOption('2002');
  await expect(page.locator('#basicBootstrapForm div').filter({ hasText: 'Date Of Birth year' }).getByRole('combobox').nth(1)).toBeVisible();
  await page.locator('#basicBootstrapForm div').filter({ hasText: 'Date Of Birth year' }).getByRole('combobox').nth(1).selectOption('February');
  await expect(page.locator('#daybox')).toBeVisible();
  await page.locator('#daybox').selectOption('14');
  await expect(page.locator('#basicBootstrapForm')).toContainText('Password');
  await expect(page.locator('#firstpassword')).toBeVisible();
  await page.locator('#firstpassword').click();
  await page.locator('#firstpassword').fill('Password@123');
  await expect(page.locator('#basicBootstrapForm')).toContainText('Confirm Password');
  await expect(page.locator('#secondpassword')).toBeVisible();
  await page.locator('#secondpassword').click();
  await page.locator('#secondpassword').fill('Password@123');
  await expect(page.getByRole('button', { name: 'Submit' })).toBeVisible();
  await page.getByRole('button', { name: 'Submit' }).click();
});